# brainlife.io funding

custom: # ['https://nsf.gov/awardsearch/showAward?AWD_ID=1734853', 
'https://nsf.gov/awardsearch/showAward?AWD_ID=1636893', 
'https://nsf.gov/awardsearch/showAward?AWD_ID=1916518', 
'https://nsf.gov/awardsearch/showAward?AWD_ID=1912270']
