#!/bin/bash

#SBATCH --job-name=track_aLIC
#SBATCH --ntasks-per-node=8
#SBATCH --mem=50G
#SBATCH --time=48:00:00

#run the tracking
app-track-between-multiple-regions/main

#run the segmentation
segViaDocker/segMain
